#!/bin/sh

echo "\n===== Installing Code Snippets and Templates =====\n"

if NOEXEC_DISABLE=1 rake clean uninstall install
then
  echo "\n*** Restart Xcode/AppCode to load the new code snippets and templates.  The templates are available under the Cedar section. ***\n"
else
  echo "\n*** It seems something went wrong installing the code snippets and templates.  Check the build output for errors. ***\n"
  exit 1
fi
