#import <Foundation/Foundation.h>

FOUNDATION_EXPORT double Cedar_iOS_FrameworkVersionNumber;

FOUNDATION_EXPORT const unsigned char Cedar_iOS_FrameworkVersionString[];

#import <Cedar/NSInvocation+Cedar.h>
#import <Cedar/Argument.h>
#import <Cedar/ValueArgument.h>
#import <Cedar/AnyInstanceArgument.h>
#import <Cedar/ReturnValue.h>
#import <Cedar/AnyArgument.h>
#import <Cedar/AnyInstanceOfClassArgument.h>
#import <Cedar/AnyInstanceConformingToProtocolArgument.h>
#import <Cedar/CDRProtocolFake.h>
#import <Cedar/CedarDoubles.h>
#import <Cedar/CDRSpy.h>
#import <Cedar/CDRClassFake.h>
#import <Cedar/HaveReceived.h>
#import <Cedar/CedarDouble.h>
#import <Cedar/RejectedMethod.h>
#import <Cedar/StubbedMethod.h>
#import <Cedar/CDRFake.h>
#import <Cedar/CedarApplicationDelegate.h>
#import <Cedar/Cedar-iOS.h>
#import <Cedar/Base.h>
#import <Cedar/BeCloseTo.h>
#import <Cedar/BeFalsy.h>
#import <Cedar/BeGreaterThan.h>
#import <Cedar/BeGTE.h>
#import <Cedar/BeInstanceOf.h>
#import <Cedar/BeLessThan.h>
#import <Cedar/BeLTE.h>
#import <Cedar/BeNil.h>
#import <Cedar/BeSameInstanceAs.h>
#import <Cedar/BeTruthy.h>
#import <Cedar/ConformTo.h>
#import <Cedar/Equal.h>
#import <Cedar/Exist.h>
#import <Cedar/RaiseException.h>
#import <Cedar/RespondTo.h>
#import <Cedar/StringifiersBase.h>
#import <Cedar/StringifiersContainer.h>
#import <Cedar/ComparatorsBase.h>
#import <Cedar/ComparatorsContainer.h>
#import <Cedar/CompareEqual.h>
#import <Cedar/CompareGreaterThan.h>
#import <Cedar/ComparatorsContainerConvenience.h>
#import <Cedar/CompareCloseTo.h>
#import <Cedar/ActualValue.h>
#import <Cedar/CedarMatchers.h>
#import <Cedar/CedarComparators.h>
#import <Cedar/CedarStringifiers.h>
#import <Cedar/MatcherTemplate.h>
#import <Cedar/ShouldSyntax.h>
#import <Cedar/CDRVersion.h>
#import <Cedar/CDRExample.h>
#import <Cedar/CDRExampleBase.h>
#import <Cedar/CDRExampleGroup.h>
#import <Cedar/CDRExampleParent.h>
#import <Cedar/CDRFunctions.h>
#import <Cedar/CDRHooks.h>
#import <Cedar/CDRSharedExampleGroupPool.h>
#import <Cedar/CDRSpec.h>
#import <Cedar/CDRSpecFailure.h>
#import <Cedar/Cedar.h>
#import <Cedar/CDRSpecHelper.h>
#import <Cedar/CDRTypeUtilities.h>
#import <Cedar/CDRSpyInfo.h>
#import <Cedar/BeEmpty.h>
#import <Cedar/Contain.h>
#import <Cedar/AnInstanceOf.h>
#import <Cedar/UIGeometryCompareEqual.h>
#import <Cedar/UIGeometryStringifiers.h>
#import <Cedar/UIKitComparatorsContainer.h>
#import <Cedar/NSMethodSignature+Cedar.h>
#import <Cedar/CDRBlockHelper.h>
#import <Cedar/CDRNil.h>
#import <Cedar/CedarDoubleImpl.h>
